/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Payslip */
        post: operations["upload_payslip_api_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payslips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Payslips */
        get: operations["list_payslips_api_payslips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payslips/{payslip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Payslip */
        delete: operations["delete_payslip_api_payslips__payslip_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rate-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Rate Limits */
        get: operations["rate_limits_api_rate_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_payslip_api_upload_post */
        Body_upload_payslip_api_upload_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /**
         * ChatHistoryMessage
         * @description Un message déjà échangé dans la conversation, tel que le frontend
         *     le garde (voir ChatPanel.tsx's `messages` state) — rôle + contenu
         *     texte seulement. Pas de tool_calls/sources : rejouer le raisonnement
         *     interne d'un tour précédent n'apporte rien au LLM, seul le texte
         *     échangé compte pour comprendre une question de suivi.
         */
        ChatHistoryMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * History
             * @default []
             */
            history: components["schemas"]["ChatHistoryMessage"][];
        };
        /** ChatResponse */
        ChatResponse: {
            /** Reply */
            reply: string;
            /** Sources */
            sources?: components["schemas"]["ChatSource"][] | null;
        };
        /**
         * ChatSource
         * @description Une source RAG citée dans une réponse du chat : le mois du bulletin
         *     d'où vient l'extrait, et l'extrait de texte lui-même. Affichage
         *     structuré côté frontend, indépendant de ce que le LLM choisit d'écrire
         *     dans le texte de sa réponse (qui reste par ailleurs instruit de citer
         *     sa source, voir _build_system_prompt() — les deux ne sont pas
         *     redondants : l'un est fiable mécaniquement, l'autre ne l'est pas).
         */
        ChatSource: {
            /** Mois Annee */
            mois_annee: string;
            /** Extrait */
            extrait: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /**
         * Payslip
         * @description Table SQLite : version persistée d'un bulletin, avec le texte brut
         *     conservé pour être ré-indexé dans ChromaDB si besoin.
         */
        Payslip: {
            /** Id */
            id?: number | null;
            /** Mois Annee */
            mois_annee: string;
            /** Nom Entreprise */
            nom_entreprise?: string | null;
            /** Salaire Brut */
            salaire_brut: number;
            /** Net Imposable */
            net_imposable: number;
            /** Net A Payer */
            net_a_payer: number;
            /** Total Cotisations Salariales */
            total_cotisations_salariales: number;
            /** Total Cotisations Patronales */
            total_cotisations_patronales: number;
            /** Cotisations Retraite */
            cotisations_retraite: number;
            /** Prelevement Source */
            prelevement_source: number;
            /**
             * Raw Text
             * @description Texte brut extrait du PDF, source pour le RAG
             */
            raw_text: string;
            /** Filename */
            filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** RateLimitStatus */
        RateLimitStatus: {
            /** Remaining */
            remaining: number;
            /** Limit */
            limit: number;
            /**
             * Reset At
             * Format: date-time
             */
            reset_at: string;
        };
        /** RateLimitsResponse */
        RateLimitsResponse: {
            upload: components["schemas"]["RateLimitStatus"];
            chat: components["schemas"]["RateLimitStatus"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             * @constant
             * @enum {string}
             */
            token_type: "bearer";
            /** Expires In */
            expires_in: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_payslip_api_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_payslip_api_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payslip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_payslips_api_payslips_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payslip"][];
                };
            };
        };
    };
    delete_payslip_api_payslips__payslip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                payslip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rate_limits_api_rate_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateLimitsResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
